---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-operator.fullname" . }}
  labels:
    {{- include "helm-operator.labels" . | nindent 4 }}
  annotations:
    fluxcd.io/automated: "true"
spec:
  selector:
    matchLabels:
      {{- include "helm-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm-operator.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: cloud-training
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
