---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-operator.fullname" . }}
  labels:
    {{- include "helm-operator.labels" . | nindent 4 }}
  annotations:
    fluxcd.io/automated: "true"
spec:
  selector:
    matchLabels:
      {{- include "helm-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm-operator.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: cloud-training
        image: gonzalobarbitta/cloud-training:1.0.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
