---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-operator.fullname" . }}
spec:
  type: LoadBalancer
  selector:
    {{- include "helm-operator.selectorLabels" . | nindent 4 }}
  ports:
    - port: 8080
      targetPort: 80