---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: helm-operator
  namespace: default
spec:
  chart:
    repository: https://github.com/gonzalobarbitta/helm-operator
    ref: master
    path: charts/helm-operator