---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: helm-operator
  annotations:
    fluxcd.io/automated: "true"
spec:
  chart:
    git: https://github.com/gonzalobarbitta/helm-operator
    ref: master
    path: charts/helm-operator
  values:
    image:
      repository: gonzalobarbitta/cloud-training
      tag: '1.0.7'
